// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bviysdljiawkvxqnewhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aXlzZGxqaWF3a3Z4cW5ld2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjAxNzQsImV4cCI6MjA2MjU5NjE3NH0.z22cvw7hkave-q9nheAA7GknpXf_2eX5TokerHdcBS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);